vpkserver/config/routes.rb
Vpkserver::Application.routes.draw do
  resources :samples
  resource :weixin
  resources :recs
  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  root :to => 'recs#index'

  match "users/:uid" => "users#show"
end

vpkserver/app/models/sample.rb
class Sample
  include MongoMapper::Document

  key :content, String
  key :type, Integer
  key :created_at, Time
end

vpkserver/app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.order("created_at ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @samples }
    end
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @sample = Sample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.json
  def new
    @sample = Sample.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:id])
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(params[:sample])
    @sample.created_at = Time.now
    respond_to do |format|
      if @sample.save
        format.html { redirect_to new_sample_path, notice: 'Sample was successfully created.' }
        format.json { render json: @sample.errors, status: :save_successlly}
      else
        format.html { render action: "new" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.json
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to samples_url }
      format.json { head :no_content }
    end
  end
end

vpkserver/app/helpers/samples_helper.rb
module SamplesHelper
end

vpkserver/app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.number_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vpkserver/app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

vpkserver/app/views/samples/index.html.erb
<h1>Listing samples</h1>
<%= link_to '新段子/台词', new_sample_path %>
<br>
<br>
<table class="table table-bordered table-striped">
  <tr>
    <th width="500px">Content</th>
    <th width="100px">Type</th>
    <th width="40px"></th>
    <th width="40px"></th>
  </tr>

<% @samples.reverse_each do |sample| %>
  <tr>
    <td style="max-width:500px;padding:5px"><%= sample.content %></td>
    <% if sample.type == 1 %>
    <% 	@type = "笑话" %>
    <% elsif sample.type == 5 %>
    <% 	@type = "三行情书" %>
    <% else %>
    <% 	@type = "台词" %>
    <% end %>
    <td style="text-align:center"><%= sample.type %> (<%= @type %>)</td>
    <td style="text-align:center"><%= link_to '编辑', edit_sample_path(sample), :class => 'btn btn-primary' %></td>
    <td style="text-align:center"><%= link_to '删除', sample, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

vpkserver/app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

vpkserver/app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @sample.content %>
</p>

<p>
  <b>Type:</b>
  <%= @sample.type %>
</p>


<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>