vpkserver/config/routes.rb
Vpkserver::Application.routes.draw do
  resources :samples
  resource :weixin
  resources :recs
  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  root :to => 'recs#index'

  match "users/:uid" => "users#show"
end

vpkserver/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

vpkserver/app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'About', page_path('about') %></li>
</ul>

vpkserver/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Vpkserver</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
					<div class="brand" href="#">麦萌管理界面</div>
					<div class="nav-collapse">
						<ul class="nav">
							<li>
								<%= link_to "录音", recs_path %>
							</li>
							<li>
								<%= link_to "段子", samples_path %>
							</li>
							<li>
								<%= link_to "统计", basic_line_charts_path %>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="span12">
					<%= yield %>
				</div>
			</div>
		</div>
	</body>
</html>